"""added models

Revision ID: 70e5ab8064be
Revises: 
Create Date: 2024-03-25 20:33:16.495882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e5ab8064be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('clipboarditems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clipboarditems_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clipboarditems'))
    )
    op.create_table('clipboarditemtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clipboard_item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clipboard_item_id'], ['clipboarditems.id'], name=op.f('fk_clipboarditemtags_clipboard_item_id_clipboarditems')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_clipboarditemtags_tag_id_tags')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clipboarditemtags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clipboarditemtags')
    op.drop_table('clipboarditems')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
